---
title: "' ' は ' <name1> ' から継承されるため、' Catch ' ブロックに到達しませんでした。 <name2>"
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 06f3b3cb69d2df5d123879fa0df3dffcdc661678
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 09/23/2020
ms.locfileid: "91084581"
---
# <a name="catch-block-never-reached-because-name1-inherits-from-name2"></a>' ' は ' \<name1> ' から継承されるため、' Catch ' ブロックに到達しませんでした。 \<name2>

コード内の `Catch` ブロックに到達することはありません。  
  
 既定では、このメッセージは警告です。 警告を非表示にする方法や、警告をエラーとして扱う方法の詳細については、「 [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)」を参照してください。  
  
 **エラー ID:** BC42029  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
- 余分な `Catch` ブロックを削除します。  
  
## <a name="see-also"></a>こちらもご覧ください

- [Try ブロックと Catch ブロックを使用して例外をキャッチする方法](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
