---
title: try-catch を使用して例外を処理する方法 - C# プログラミング ガイド
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
ms.openlocfilehash: adfc53cbe4fd603ac3a6de6b9a0162320d5a2e19
ms.sourcegitcommit: 5f236cd78cf09593c8945a7d753e0850e96a0b80
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 01/07/2020
ms.locfileid: "75712287"
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="a1184-102">try/catch を使用して例外を処理する方法 (C# プログラミング ガイド)</span><span class="sxs-lookup"><span data-stu-id="a1184-102">How to handle an exception using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="a1184-103">[try-catch](../../language-reference/keywords/try-catch.md) ブロックの目的は、作業コードによって生成された例外をキャッチし、処理することです。</span><span class="sxs-lookup"><span data-stu-id="a1184-103">The purpose of a [try-catch](../../language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="a1184-104">例外によっては、`catch` ブロックで処理し、例外を再スローせずに問題を解決できるものもありますが、多くの場合、適切な例外がスローされるようにする必要があります。</span><span class="sxs-lookup"><span data-stu-id="a1184-104">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="a1184-105">例</span><span class="sxs-lookup"><span data-stu-id="a1184-105">Example</span></span>  
 <span data-ttu-id="a1184-106">この例の <xref:System.IndexOutOfRangeException> は最も適切な例外というわけではありません。呼び出し元から `index` 引数が渡されてエラーが発生しているため、より適切なメソッドは <xref:System.ArgumentOutOfRangeException> になります。</span><span class="sxs-lookup"><span data-stu-id="a1184-106">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#5](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#5)]  
  
## <a name="comments"></a><span data-ttu-id="a1184-107">コメント</span><span class="sxs-lookup"><span data-stu-id="a1184-107">Comments</span></span>  
 <span data-ttu-id="a1184-108">例外を発生させるコードは `try` ブロックに囲まれています。</span><span class="sxs-lookup"><span data-stu-id="a1184-108">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="a1184-109">`IndexOutOfRangeException` が発生した場合にこれを処理するための `catch` ステートメントが、すぐ後に追加されています。</span><span class="sxs-lookup"><span data-stu-id="a1184-109">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="a1184-110">`catch` ブロックは `IndexOutOfRangeException` を処理し、代わりにより適切な `ArgumentOutOfRangeException` 例外をスローします。</span><span class="sxs-lookup"><span data-stu-id="a1184-110">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="a1184-111">呼び出し元にできるだけ多くの情報を提供するため、元の例外を新しい例外の <xref:System.Exception.InnerException%2A> として指定することを検討してください。</span><span class="sxs-lookup"><span data-stu-id="a1184-111">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="a1184-112"><xref:System.Exception.InnerException%2A> プロパティは [readonly](../../language-reference/keywords/readonly.md) であるため、新しい例外のコンストラクターで割り当てる必要があります。</span><span class="sxs-lookup"><span data-stu-id="a1184-112">Because the <xref:System.Exception.InnerException%2A> property is [readonly](../../language-reference/keywords/readonly.md), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="a1184-113">関連項目</span><span class="sxs-lookup"><span data-stu-id="a1184-113">See also</span></span>

- [<span data-ttu-id="a1184-114">C# プログラミング ガイド</span><span class="sxs-lookup"><span data-stu-id="a1184-114">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="a1184-115">例外と例外処理</span><span class="sxs-lookup"><span data-stu-id="a1184-115">Exceptions and Exception Handling</span></span>](./index.md)
- [<span data-ttu-id="a1184-116">例外処理</span><span class="sxs-lookup"><span data-stu-id="a1184-116">Exception Handling</span></span>](./exception-handling.md)
